### PR TITLE
remove members that resigned their BU membership

### PR DESCRIPTION
**Pull request by torusJKL**
Removing the following members that resigned their BU membership

lunar: https://bitco.in/forum/threads/bitcoin-unlimited-membership-join-us.208/page-16#post-88562
mengerian: https://bitco.in/forum/threads/bitcoin-unlimited-membership-join-us.208/page-16#post-89633
deadalnix: https://bitco.in/forum/threads/gold-collapsing-bitcoin-up.16/page-1378#post-89851
todu: https://twitter.com/todu77/status/1110379550964412416

### CODE REVIEW

**Comment by torusJKL** [comment]
Removing kyuupichan who sent his resignation to the BU president in private.

**Comment by torusJKL** [comment]
micropresident: https://shablag.com/article/every-new-beginning/

**Comment by AndrewClifford** [comment]
Hi @torusJKL 
I would be grateful if you also add micropresident to the list.
Hopefully that will be the last for a while.

**Comment by torusJKL** [comment]
Hi @AndrewClifford 
micropresident is already removed with commit [333402e](https://github.com/BitcoinUnlimited/BitcoinUnlimitedWeb/pull/206/commits/333402ed1f31301c3db4e32b2ed7d1634df1a8ee).
But I could squash all the commits together if that's what you mean.

**Comment by sickpig** [comment]
@solex would you mind approving the PR so that I could merge and deploy?

**Comment by AndrewClifford** [comment]
@torusJKL @sickpig 
I am happy with these changes. Please proceed.

**Pull request merged**
