### PR TITLE
Add German translation for Home and Download page

### PR DESCRIPTION
**Pull request by satoshisSockpuppet**
Adds a German translation for the website for the "Home" and "Download" section, FAQ is still in English.

I hope the file naming is correct.

### CODE REVIEW

**Comment by thofmann** [comment]
Thanks for the PR! It looks like the right file name and structure at a glance.

**Comment by thofmann** [comment]
Retesting.

**Comment by torusJKL** [comment]
I can help translating to German.
Is there a reason this has not been merged?

**Comment by thofmann** [comment]
Thanks @torusJKL 

I will merge this PR now.

**Pull request merged**
