### PR TITLE
Fix name of 1.0.0.1 binaries

### PR DESCRIPTION
**Pull request by sickpig**
In the last commit we upload 1.0.0.1 but mark them as 1.0.0

### CODE REVIEW

**Comment by thofmann** [comment]
Should the signed statement be updated for the new filenames? The hashes do not change, but the file names have.

This is the statement still being used: https://github.com/BitcoinUnlimited/BitcoinUnlimitedWeb/blob/9c63dca8e5ab2897efe296c1b071373ed8484eec/src/public/views/components/download/signatures.jsx#L53-L67

image

**Comment by sickpig** [comment]
@thofmann you are right. 

I'm on it

**Comment by sickpig** [comment]
updated and rebased.

**Comment by thofmann** [comment]
Thanks for the PR and the message update! I have verified the signatures and will be merging now.

**Pull request merged**
