### PR TITLE
Add donate page

### PR DESCRIPTION
**Pull request by jacksarrocco**
I've started working on the new donation page. I created the new page, with new route, strings and a qr code image for the address. But I don't know where to have the link on the main menu, since it's already full. Check it out

### CODE REVIEW

**Comment by thofmann** [comment]
Concept ACK

Thanks for the PR! I'll look at these changes soon and probably suggest a few changes. I'm also going to check with the BU officers to confirm which address they'd like to use for donations.

**Comment by jacksarrocco** [comment]
> I'm also going to check with the BU officers to confirm which address they'd like to use for donations.

I found the address [here on a Reddit post](https://www.reddit.com/r/btc/comments/57bzow/how_do_i_donate_bitcoin_to_the_bitcoin_unlimited/d8qrwx1)

**Comment by thofmann** [comment]
Confirmation that `36XTMVtgJqqNYymsSvRonpUsbZRGkm1jvX` is the correct address:

image

**Comment by thofmann** [comment]
I've also verified that the QR code matches.

**Comment by thofmann** [comment]
@jacksarrocco I've suggested a few changes here: https://github.com/jacksarrocco/BitcoinUnlimitedWeb/pull/1

My PR would:

* Fix some formatting (spaces instead of tabs)
* Move the intro paragraph below the header (looks better to me)
* Add a link to the page in the footer

**Comment by jacksarrocco** [comment]
We leave just that link on the footer,  don't we?

**Comment by thofmann** [comment]
>We leave just that link on the footer, don't we?

What do you mean?

**Comment by jacksarrocco** [comment]
Like, the only way to go on that page will be by clicking the link on the footer, right?

**Comment by thofmann** [comment]
Right.

**Pull request merged**
