### PR TITLE
release 1.0.1.2

### PR DESCRIPTION
**Pull request by gandrewstone**

### CODE REVIEW

**Comment by thofmann** [comment]
No signatures from @sickpig and @deadalnix?

**Comment by gandrewstone** [comment]
1.0.1.2 has been open sourced and signed (no changes to the binaries) and the minor changes to that patch that emerged from open review have been released in 1.0.1.3.  Please merge the PR.

**Comment by gandrewstone** [comment]
also please check that the new links to the binary files in github are correct -- I could not check them because the WebDownloads repo has not yet been marged

**Comment by sickpig** [comment]
@thofmann 

@gandrewstone added the missing signs (sickpig's and deadalnix's) for ver 1.0.1.2. 

The source tree for the 1.0.1.2 could be found here: https://github.com/BitcoinUnlimited/BitcoinUnlimited/tree/1.0.1.2

The PR has been modified adding a the new 1.0.1.3 release. This new relase addresses minor and cosmetic issues reported when the 1.0.1.2 release patch came under full review, for more detail see:

https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/390

**Pull request merged**
